### PR TITLE
Standardize anonymous functions to arrow functions

### PR DESCRIPTION
**Pull request by maxrabin**

### CODE REVIEW

**Comment by spaze** [comment]
Thanks @maxrabin, your pull request has no description, can you please provide one? I'd like to know what's the reason behind this besides we're already using it elsewhere in the code. Thanks!

**Comment by hugmanrique** [comment]
Also, we can and _should_ use Object.keys(...).forEach instead of .map as we aren't doing anything with the returned values.

**Comment by ScottHelme** [comment]
@hugmanrique please feel free to create a PR! 👍

**Comment by ScottHelme** [comment]
I've incorporated the PR @maxrabin, the suggestion from @hugmanrique and some other changes in https://github.com/securityheaders/security-headers-cloudflare-worker/commit/6cb3d7e1763b9c3259ebd97b6f5c255cd2658ecb. Thanks for the participation! 👍

**Pull request closed without merging**
